name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        sudo apt install android-sdk
        sudo apt install python3

        python -m pip install --upgrade pip
        pip install python-for-android Cython

    - name: Build APK
      run: |
        p4a apk --private . --package=Test --name "Test" --version 0.1 --bootstrap=sdl2 --requirements=kivy,numpy,requests --arch=armeabi-v7a
      env:
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}

