name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-6858069_latest.zip
        unzip commandlinetools-linux-6858069_latest.zip -d android-sdk
        yes | android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=android-sdk "platforms;android-29" "build-tools;29.0.3" "ndk;21.3.6528147"
        python -m pip install --upgrade pip
        pip install -r kivy numpy requests
        pip install python-for-android==2023.9.16 Cython

    - name: Build APK
      run: |
        p4a apk --private . --package=Test --name "Test" --version 0.1 --bootstrap=sdl2 --requirements=kivy,numpy,requests --arch=armeabi-v7a
      env:
        P4A_RELEASE_KEYALIAS: ${{ secrets.P4A_RELEASE_KEYALIAS }}
        P4A_RELEASE_KEYSTORE_PASSWD: ${{ secrets.P4A_RELEASE_KEYSTORE_PASSWD }}
        P4A_RELEASE_KEYALIAS_PASSWD: ${{ secrets.P4A_RELEASE_KEYALIAS_PASSWD }}

    - name: Output Gradle logs if build fails
      if: failure()
      run: cat /home/runner/.local/share/python-for-android/dists/unnamed_dist_1/build/build.log
